cuda: 0
method: GREEN
num_epochs: 10
data_format:
    fps: 35
    batch_size: 1
    slice_interval: 160
    step: 20
train: # Non-DNN method will ignore this parameter 'train'
    dataset:
        loader: UBFC_Phys
        path: D:\BaiduNetdiskDownload\UBFC-PHYs_1-12
test:
    dataset:
        loader: UBFC_Phys
        path: D:\BaiduNetdiskDownload\UBFC-PHYs_1-12
compression:
    fps: 30
    # zero means the original resolution of the video
    resolution_ratio: 0
    codec: MPV4
    rate: 4000
    
