cuda: 0
method: PhysNet
data_format:
    fps: 30
    batch_size: 1
    slice_interval: 90
    step: 40

train: # Non-DNN method will ignore this parameter 'train'
    num_epochs: 500
    min_test_loss: 0.11
    min_train_loss: 0.09
    optim:
        package: torch.optim
        name: Adam
        params:
            lr: 0.01
    loss:
        package: loss.phys_net
        name: PhyNetLoss
    dataset:
        force_clear_cache: False
        load_to_memory: False
        loader: UBFC_Phys
        path: D:\dataset\compression\UBFC-PHYs
        # loader: ZJXU
        # path: D:\dataset\compression\ZJXU\stationary
        # path: D:\dataset\compression\ZJXU\wark
        dataloader:
            num_workers: 12
            pin_memory: True
            shuffle: False
test:
    dataset:
        force_clear_cache: False
        loader: UBFC_Phys
        path: D:\dataset\compression\UBFC-PHYs_test
        # loader: ZJXU
        # path: D:\dataset\compression\ZJXU\stationary_test
        # path: D:\dataset\compression\ZJXU\wark_test
        load_to_memory: False
        dataloader:
            num_workers: 12
            pin_memory: False
            shuffle: False

    
